language: php
# also test against HHVM, but require "trusty" and ignore errors
jobs:
  include:
    - language: php
      php: 7.1
    - language: php
      php: 7.2
    - language: php
      php: 7.3
    - language: php
      php: 7.4
    - language: php
      php: hhvm
      dist: trusty
    - language: node_js
      node_js: 8
    - language: node_js
      node_js: 10
    - language: node_js
      node_js: 11
    - language: node_js
      node_js: 12
    - language: node_js
      node_js: 13
  allow_failures:
    - php: hhvm

cache:
  npm: false

stages:
  - name: php-build
    if: language = 'php'
    before_script:
    - composer self-update
    - composer update --prefer-source
    script:
      - vendor/bin/phpunit --testsuite travis-ci
      - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
    after_script:
      - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
  - name: node-build
    if: language = 'node_js'
    script:
      - npm install
  - name: test-test-test
    script:
      - echo "$language"