language: php
jobs:
  include:
    # Use a YAML alias to prevent redundancy.
    # https://github.com/travis-ci/travis-ci/issues/8295#issuecomment-454167006
    - &phpbuild
      stage: php-build
      language: php
      php: 7.3
      before_script:
      - composer self-update
      - composer update --prefer-source
      script:
        - vendor/bin/phpunit --testsuite travis-ci
        - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
      after_script:
        - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
    - &nodebuild
      stage: node-build
      language: node_js
      install: skip
      node_js: 10
      script:
        - npm install
        - npm run dev
      after_failure:
        - echo "This is after_failure!!!"
        - cat /home/travis/.npm/_logs/*-debug.log
      after_success:
        - echo "This is after_success!!!"
        - cat /home/travis/.npm/_logs/*-debug.log
      after_script:
        - echo "This is after_script!!!"
        - cat /home/travis/.npm/_logs/*-debug.log
    - <<: *phpbuild
      php: 7.4
    - <<: *nodebuild
      node_js: 11
    - <<: *nodebuild
      node_js: 12
    - <<: *nodebuild
      node_js: 13

cache:
  npm: false