language: php

php:
  - 7.1
  - 7.2
  - 7.3

# also test against HHVM, but require "trusty" and ignore errors
matrix:
  include:
    - php: hhvm
      dist: trusty
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer update --prefer-source

script:
  - vendor/bin/phpunit --testsuite travis-ci
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
