name: Continuous Integration

on: [push, pull_request]

jobs:
  quality:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-version: ['8.0', '8.1', '8.2', '8.3']
        node-version: [16.x, 17.x, 18.x, 19.x, 20.x, 21.x, 22.x, 23.x, 24.x]
    name: PHP ${{ matrix.php-version }} | Node ${{ matrix.node-version }} Test on ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: ${{ matrix.php-version }}
      
      - name: Check PHP Version
        run: php -v

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: PHP Unit tests
        run: |
         vendor/bin/phpunit --testsuite travis-ci
         vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install NPM dependencies
        run: npm install
      
      - name: Build Fomantic-UI
        run: |
          cd node_modules/fomantic-ui
          npx gulp install
      
      - name: Compile assets
        run: npm run dev
      
      - name: Upload code coverage data
        run: php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover